title: Gadget News
email: tursynbekovee@mail.ru
description: Автогенерируемые статьи про гаджеты и технологии
baseurl: ""
url: "https://tee-webhub.github.io/TEETech"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Gadget News
